version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-stretch-node-browsers
    steps:
      - checkout
      - run:
          name: Configure Bundler
          command: |
            BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")
            echo "Installing bundler: $BUNDLER_VERSION"
            sudo gem update --system --no-user-install
            sudo gem install bundler:$BUNDLER_VERSION
      - run: sudo bundle install
      - run: sudo bundle exec rake spec
