version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-stretch-node-browsers
    steps:
      - checkout
      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler
      - run: bundle install
      - run: bundle exec rake spec
